CREATE TABLE IF NOT EXISTS metric (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL,
  help TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS label (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS label_value (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  label_id INTEGER NOT NULL REFERENCES label(id) ON DELETE CASCADE,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS series (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  metric_id INTEGER NOT NULL REFERENCES metric(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS label_set (
  label_value_id INTEGER NOT NULL REFERENCES label_value(id),
  series_id INTEGER NOT NULL REFERENCES series(id) ON DELETE CASCADE,
  PRIMARY KEY (label_value_id, series_id)
);
